name: ags # you probably want to 'snapcraft register <name>'
version: '3.4.1.14' # just for humans, typically '1.2+git' or '1.3.2'
summary: adventure game studio engine for playing ags games. # 79 char long summary
description: |
  Run adventure games made in Adventure Game Studio, by using the ags linux engine.
  When installed, just run ags in the folder that contains the game!

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

# architectures: [amd64, i386]

apps:
  ags:
    command: desktop-launch alsa-launch $SNAP/bin/ags
    plugs:
      - home
      - pulseaudio
      - x11
      - opengl

parts:
  alsa:
    after: [alsa-lib, alsa-plugins]
  alsa-lib:
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-alisp
    - --disable-aload
    - --disable-python
    - --disable-rawmidi
    - --disable-static
    - --disable-topology
    - --disable-ucm
    - --enable-symbolic-functions
  alsa-plugins:
    after: [alsa-lib]
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --disable-arcamav
    - --disable-avcodec
    - --disable-jack
    - --disable-mix
    - --disable-oss
    - --disable-usbstream
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-static
    - LDFLAGS=-L$SNAPCRAFT_STAGE/usr/lib
  ags:
    after: [alsa, desktop-glib-only]
    plugin: make
    make-parameters:
      - --directory=Engine
    make-install-var: PREFIX
    source-type: tar
    stage:
      - -usr/share/alsa/alsa.conf
      - -usr/share/alsa/cards/USB-Audio.conf
      - -usr/share/alsa/cards/aliases.conf
      - -usr/share/alsa/pcm/dmix.conf
      - -usr/share/alsa/pcm/dsnoop.conf
      - -usr/share/alsa/pcm/surround21.conf
      - -usr/share/alsa/pcm/surround40.conf
      - -usr/share/alsa/pcm/surround41.conf
      - -usr/share/alsa/pcm/surround50.conf
      - -usr/share/alsa/pcm/surround51.conf
      - -usr/share/alsa/pcm/surround71.conf

    source: https://github.com/adventuregamestudio/ags/archive/v.3.4.1.14.tar.gz
    build-packages:
      - g++
      - gcc
      - make
      - libpng12-dev 
      - git
      - debhelper 
      - build-essential
      - pkg-config 
      - libaldmb1-dev 
      - libfreetype6-dev 
      - libtheora-dev 
      - libvorbis-dev
      - libogg-dev
    stage-packages:
      - libx11-6
      - libxcursor1
      - libpng12-0
      - libaldmb1
      - libfreetype6
      - libtheora0
      - libogg0
      - libvorbis0a
      - libvorbisfile3

