name: ags # you probably want to 'snapcraft register <name>'
version: '3.4.1.14' # just for humans, typically '1.2+git' or '1.3.2'
summary: adventure game studio engine for playing ags games. # 79 char long summary
description: |
  Run adventure games made in Adventure Game Studio, by using the ags linux engine.
  When installed, just run ags in the folder that contains the game!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  ags:
    command:  desktop-launch alsa-launch allegro-modules-launch ${SNAP}/bin/ags
    plugs:
      - desktop
      - desktop-legacy
      - home
      - pulseaudio
      - x11
      - opengl

parts:

  lib-alleg:
    after: [alsa, desktop-glib-only]
    source: https://github.com/adventuregamestudio/lib-allegro.git
    source-type: git
    source-branch: allegro-4.4.2-agspatch
    plugin: cmake
    override-build: |
      snapcraftctl build
      cat > allegro-modules-launch <<EOF
      #!/bin/bash
      if [ "\$SNAP_ARCH" == "amd64" ]; then
        ARCH="x86_64-linux-gnu"
      elif [ "\$SNAP_ARCH" == "armhf" ]; then
        ARCH="arm-linux-gnueabihf"
      elif [ "\$SNAP_ARCH" == "arm64" ]; then
        ARCH="aarch64-linux-gnu"
      else
        ARCH="\$SNAP_ARCH-linux-gnu"
      fi

      export ALLEGRO_MODULES="\$SNAP/usr/lib/\$ARCH/allegro/4.4.2"
      exec "\$@"
      EOF

      install -m755 -D -t $SNAPCRAFT_PART_INSTALL/bin allegro-modules-launch

    configflags:
      - -DWANT_DOCS=0
      - -DALLEGRO_WITH_ALSADIGI=1
    build-packages:
      - g++
      - gcc
      - make
      - libpng12-dev 
      - git
      - debhelper 
      - build-essential
      - pkg-config 
      - libaldmb1-dev 
      - libfreetype6-dev 
      - libtheora-dev 
      - libvorbis-dev
      - libogg-dev
      - libasound2-dev

  ags:
    after: [alsa, desktop-glib-only,lib-alleg]
    plugin: make
    make-parameters:
      - --directory=Engine
    make-install-var: PREFIX
    source-type: tar
    source: https://github.com/adventuregamestudio/ags/archive/v.3.4.1.14.tar.gz
    override-pull: |
      snapcraftctl pull
#      sed -i '605s/DIGI_NONE/DIGI_ALSA/' $SNAPCRAFT_PART_SRC/Engine/main/engine.cpp
    build-packages:
      - g++
      - gcc
      - make
      - libpng12-dev 
      - git
      - debhelper 
      - build-essential
      - pkg-config 
      - libaldmb1-dev 
      - libfreetype6-dev 
      - libtheora-dev 
      - libvorbis-dev
      - libogg-dev
    stage-packages:
      - libx11-6
      - libxcursor1
      - libpng12-0
      - libaldmb1
      - libfreetype6
      - libtheora0
      - libogg0
      - libvorbis0a
      - libvorbisfile3
    stage:
    - -usr/share/alsa/alsa.conf
    - -usr/share/alsa/cards/USB-Audio.conf
    - -usr/share/alsa/cards/aliases.conf
    - -usr/share/alsa/pcm/dmix.conf
    - -usr/share/alsa/pcm/dsnoop.conf
    - -usr/share/alsa/pcm/surround21.conf
    - -usr/share/alsa/pcm/surround40.conf
    - -usr/share/alsa/pcm/surround41.conf
    - -usr/share/alsa/pcm/surround50.conf
    - -usr/share/alsa/pcm/surround51.conf
    - -usr/share/alsa/pcm/surround71.conf
    - -usr/lib/x86_64-linux-gnu/libasound.so.2
    - -usr/lib/x86_64-linux-gnu/libasound.so.2.0.0

  # specify remote part build order
  alsa:
    after: [alsa-lib, alsa-plugins]
  alsa-lib:
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-alisp
    - --disable-aload
    - --disable-python
    - --disable-static
    - --disable-topology
    - --disable-ucm
    - --enable-symbolic-functions
  alsa-plugins:
    after: [alsa-lib]
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --disable-arcamav
    - --disable-avcodec
    - --disable-jack
    - --disable-mix
    - --disable-oss
    - --disable-usbstream
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-static
    - LDFLAGS=-L$SNAPCRAFT_STAGE/usr/lib
